server:
  servlet:
    context-path: /Subject-For-Springboot
#DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/letitgo?serverTimezone=Asia/Taipei
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#SessionFatory
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        
        
 